### ISSUE TITLE
"resetting" modified notebooks

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#11]
Right now it's not simple for people to go back to square one on their notebooks. Several instructors mentioned that it would be useful to be able to pull a fresh copy of a notebook / directory / etc in case they mess something up or want to start anew.

Right now, things behave weirdly when you delete / rename / etc a file and then click on the "interact" links again. I think we should come to a consensus for how to handle this situation as simply as possible.

Right now the working idea is to automatically pull backups whenever someone clicks an "interact" link. That way people can always just copy over the original notebook if they mess something up, without doing any extra pulling / deleting / etc. These backups might be in-line w/ the regular files, or stored in a `backups` folder that comes with the files you just pulled.

**Comment by SamLau95** [comment]
Another easy way to get the original for now is to just link to the notebook on Github. Eg. I'm working on lab1 and I mess up. I can look at/download https://github.com/data-8/data8assets/blob/master/labs/lab01/lab01.ipynb

This works nicely even for private repos since they can access files at data8.org. Eg. http://data8.org/data8assets/labs/lab01/lab01.ipynb

Thoughts on this?

**Comment by cboettig** [comment]
@SamLau95 Good point.  I think that is definitely good as a reference to just look at, but less good as a strategy to actually get back to square 1 in general.  (e.g. looking at the GitHub page, most of my students wouldn't know how to download the file -- there's no 'download' button (some might end up downloading the whole repo instead).  And manually uploading doesn't scale nicely if we're talking more than one file.  

In general, I think the strategy of

a) delete or rename current work
b) repeat original import command

Should get a user back to where they started, since that's the most intuitive thing to try (imho).  That this is impossible due to both permissions issue making `delete` impossible and the `interact` link refusing to re-import a file even after the earlier version was renamed (instead of deleted) is bound to cause trouble.
