### ISSUE TITLE
Suggestion for README & FAQ

### ISSUE THREAD

**Issue by cboettig** [data-8/connector-instructors#22]
A few suggestions that might improve readability / organization.  Consider:
- [ ] Adding a (linked) table of contents to the README.md
- [ ] Breaking the FAQ out into a separate FAQ.md doc in the repo, and just linking it from the README?

**Comment by choldgraf** [comment]
Damn I'm just now seeing this (a year later). These are good suggestions @cboettig and they've been implemented in the last month (more or less). More conceptual stuff is now in the site wiki, and  it's broken down by page rather than being in one mega-doc. Please keep adding suggestions etc in the future, I think this repo will be checked / used more frequently from here on.
