### ISSUE TITLE
Please install osgeo and geopy libraries for the geospatial connector

### ISSUE THREAD

**Issue by pattyf** [data-8/connector-instructors#23]
@Ryan and team, please install the following libraries for the geospaital connector. I would like to distribute an exercise based on these libraries in February (2/22). Attaching a notebook with dataset to show how they will be used.  Thanks!

The first cell in the notebook shows the libraries that I am using:
from geopy.distance import vincenty  
from osgeo import ogr, osr, gdal 
import json

[dist_area_crs_libs.zip](https://github.com/data-8/connector-instructors/files/110517/dist_area_crs_libs.zip)

**Comment by pattyf** [comment]
Hi @ryanlovett, do you have an update on this issue? I would like to be able to use these libraries in an exercise on Feb 22. Thanks, Patty

**Comment by ryanlovett** [comment]
Hi @pattyf, I'm able to install and import the required libraries in a test environment based on the data8 platform. Some of the cells in the notebook did not run because it references paths specific to your computer. I'll clear the additional libraries with John then assuming we've got the green light I'll let you know when your next server start-up will have them.

**Comment by ryanlovett** [comment]
@pattyf: The singleuser server on data8 now contains the osgeo and geopy libraries. GDAL_DATA is /opt/conda/share/gdal. You'll need to stop and start your server to see it. Let me know if it checks out and I'll push it to ds8 as well.

**Comment by pattyf** [comment]
@ryanlovett GDAL/OGR works great. Ok to close issue. Thanks much!

**Comment by ryanlovett** [comment]
Okay, great!
