### ISSUE TITLE
Write helper to convert repo and folder paths to an interact link

### ISSUE THREAD

**Issue by SamLau95** [data-8/connector-instructors#26]
Basically, we'd like to put a little helper on http://data8.org/connector-instructors so that instructors can input their repo + path(s) and get back a link.

This will help avoid spelling errors and other common mistakes.

**Comment by choldgraf** [comment]
Hey - I recently heard about [Binder](http://mybinder.org/), and wanted to give it a shot. It's pretty cool! As a start, I wrote a short notebook that makes url conversion a bit easier (still clunky since you have to open a notebook, but that's not so bad since they'd need to click a URL anyway). All you should need to do is go here:

http://mybinder.org/repo/choldgraf/connector-instructors/ntbk/url_to_interact.ipynb

And follow the instructions. What do you think?

maybe @elaine84 would be interested in this as well, as on-the-fly notebooks are pretty nifty :)

**Comment by elaine84** [comment]
@choldgraf this is cool!  I think it's great as an immediate thing that would be useful to instructors.  You might want to try out some more examples, I think there's a bug that doesn't properly handle deeper file paths (e.g., a notebook in a folder in a repo such as https://github.com/data-8/smart-cities-connector/blob/gh-pages/labs_in_progress/Minilab3%20-%20Mapping%20travel%20times.ipynb).  

Chris et al, are you also interested in looking into Binder some more?  We might be able to learn something from its implementation.  (Presently it looks like they can support 700 containers at a time; when I looked at their status they had 628/700 available.)  We might want to open another issue about this.

@SamLau95 what do you think?  For some added context, it's not obvious to me that we want to continue using these interact links as part of the long-term workflow we envision (or to make a less strong statement, I could imagine depending less on the interact links for content distribution, while also supporting them since they seem useful).

**Comment by SamLau95** [comment]
Binder does look cool!

I agree that we probably want to have a different default file distribution
system.

This notebook looks useful for the time being.
ᐧ

On Thu, Feb 18, 2016 at 11:32 AM, elaine84 notifications@github.com wrote:

> @choldgraf https://github.com/choldgraf this is cool! I think it's
> great as an immediate thing that would be useful to instructors. You might
> want to try out some more examples, I think there's a bug that doesn't
> properly handle deeper file paths (e.g., a notebook in a folder in a repo
> such as
> https://github.com/data-8/smart-cities-connector/blob/gh-pages/labs_in_progress/Minilab3%20-%20Mapping%20travel%20times.ipynb).
> 
> Chris et al, are you also interested in looking into Binder some more? We
> might be able to learn something from its implementation. (Presently it
> looks like they can support 700 containers at a time; when I looked at
> their status they had 628/700 available.) We might want to open another
> issue about this.
> 
> @SamLau95 https://github.com/SamLau95 what do you think? For some added
> context, it's not obvious to me that we want to continue using these
> interact links as part of the long-term workflow we envision (or to make a
> less strong statement, I could imagine depending less on the interact links
> for content distribution, while also supporting them since they seem
> useful).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/26#issuecomment-185881102
> .

## 

Sam Lau
EECS | UC Berkeley
Project Mentor | Blueprint, Technology for Nonprofits
_samlau95@gmail.com samlau95@gmail.com_

**Comment by ryanlovett** [comment]
It'd be good to get Yuvi's feedback since binder uses kubernetes to spawn containers.

The 700 container limit is on mybinder.org's infrastructure. One can deploy the same setup to another set of nodes.

**Comment by elaine84** [comment]
Totally agreed, I sent him a link

**Comment by choldgraf** [comment]
thanks for the thoughts everybody - I agree this is a short-term solution, just something to help people right now and buy time until something more well-thought-out is made.

Regarding Binder, we could also reach out to Jeremy Freeman, as I believe that they've done a lot of the core work on Binder. Though maybe Yuvi is also doing the same?

@elaine84 thanks for finding that bug. I've updated the notebook to be more robust to deeper file structures etc, and I also added some "example" URLs at the end that can also serve as tests of a kind. :)

Binder should just take a minute or two to update, then check the updated repo:
http://mybinder.org/repo/choldgraf/connector-instructors/ntbk/url_to_interact.ipynb

@SamLau95, maybe we should just put a link to my Binder instance in the Readme somewhere and send it out as an email? I don't see a real reason to add this notebook to the official connector-instructors repo...

**Comment by SamLau95** [comment]
Sending it via email sounds good to me.
ᐧ

On Thu, Feb 18, 2016 at 1:00 PM, Chris Holdgraf notifications@github.com
wrote:

> thanks for the thoughts everybody - I agree this is a short-term solution,
> just something to help people right now and buy time until something more
> well-thought-out is made.
> 
> Regarding Binder, we could also reach out to Jeremy Freeman, as I believe
> that they've done a lot of the core work on Binder. Though maybe Yuvi is
> also doing the same?
> 
> @elaine84 https://github.com/elaine84 thanks for finding that bug. I've
> updated the notebook to be more robust to deeper file structures etc, and I
> also added some "example" URLs at the end that can also serve as tests of a
> kind. :)
> 
> Binder should just take a minute or two to update, then check the updated
> repo:
> 
> http://mybinder.org/repo/choldgraf/connector-instructors/ntbk/url_to_interact.ipynb
> 
> @SamLau95 https://github.com/SamLau95, maybe we should just put a link
> to my Binder instance in the Readme somewhere and send it out as an email?
> I don't see a real reason to add this notebook to the official
> connector-instructors repo...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/data-8/connector-instructors/issues/26#issuecomment-185917827
> .

## 

Sam Lau
EECS | UC Berkeley
Project Mentor | Blueprint, Technology for Nonprofits
_samlau95@gmail.com samlau95@gmail.com_

**Comment by choldgraf** [comment]
there's a function to do this quickly in the `connectortools` module (though it may need to be updated for new course infrastructure) as well as a binder notebook to demo it, so I'm closing this. If we'd like a more interactive solution (e.g., a tiny javascript app) let's open the issue again if the need arises.
