### ISSUE TITLE
Update technical information in this repository + moving stuff to a wiki

### ISSUE THREAD

**Issue by choldgraf** [data-8/connector-instructors#34]
Before the new semester starts we need to do these things:

## General
- [ ] Update all technical information (links, instructions, etc) so that they're correct with the current setup of jupyterhub etc.
- [ ] Throughout all of the wiki, change `data8` to `datahub`
- [x] Migrate content to a wiki so that the "code" and "conceptual" components of this repository are nicely separated.
- [x] Update the FAQ, modularize it & give sub-headings
- [ ] Add binder links where relevant so people can interactively click on them

## Hardware Resources
- [x] Mention that nodes are shared between people. You should only use one core and if you need more, talk to the infrastructure people.
- [x] Memory restrictions - mention the thing that says how much memory you have left in the top-right
- [x] Say what happens when you hit too much memory in more detail, explain the error message, restarting kernel, etc
- [x] Warn against using multiple CPUs or n_jobs > 1
- [x]  IO - mention 10 GB limit
- [x] Multiple options: download the files within the cluster (show the connectortools download module) demo creating your own download file). OR, talk to the tech team about setting up shared disk space

## Software
- [x] Updating libraries - show that you can either ask Ryan etc to update which will take a while, or you can use the connectortools function to update it under the hood. Write a binder demo to show this.
- [x] Move interactive notebooks section so that it's in "home", explain binder, and sprinkle binder links throughout
- [x] Edit "setting up a course" to be more about setting up an account since that's really what it covers. Note that it doesn't *have* to have a github
- [x] Mention that if you want to create interact links then you need a github account.
- [x] Add a section on creating interact link.

## Tech infrastructure
- [x] Add a quick explanation of each major component of the jupyterhub process
- [x] Links for each one to go towards more in-depth information
- [x] Quick guide on using docker locally to get the jupyterhub deployment on your computer

## Workflow
- [x] There's overlap in information w/ "setting up your repo" elsewhere...remove redundancies.
- [x] Change the "add datasets" section to point them to the adding data section and add the "upload" button there...keep the information there though, so it's still a full workflow

I can do no. 2, @ryanlovett do you think we can chat briefly about no. 1 ?

**Comment by ryanlovett** [comment]
No problem, just email me your availability.

**Comment by clcarson** [comment]
### Things to add that would help connector instructors

**Creating connector servers**  (@ryanlovett ? @choldgraf ?)

- How do we explain to instructors how they can get a connector server (or hub?) set up?
- What can they get?
- How do they ask for it?
- What do their students need to do in order to get accounts?

This seems to come even before workflow. I'd love to have this info ready to send out already over the weekend if we can.

**Connector assistants and other connector resources**  (@anthonysuen, is this you & Aspen)
Right now this wiki is mostly technical information. Should we

- add information (a page?) about connector assistants
- integrate the content of the [spreadsheet](https://docs.google.com/spreadsheets/d/1gcJ_zkvkbVzOu1z1HFtIKRAfczcA5QaELNBkvcTwRLM/edit?ts=587e91b6#gid=0) of other connector instructor resources we made on Wed 

It'd seem to me to make sense to put these non-technical things here, but tell me if you'd see a better way?

**Usability**
- Does someone need a GitHub account in order to see the wiki?
- Edit the wiki?
- How about in order to create issues?

**Contact info**
- Do we mention Ryan somewhere?
- Should we still leave on Sam Lau as a point of contact, or replace him with someone else? I.e., eventually Gunjan, once we've onboarded her.

**Comment by choldgraf** [comment]
Thanks for the suggestions @clcarson, @ryanlovett and I will meet today and we can hash out any details that I'll then add to the wiki.

Once all the information is up there, I'll ping this issue again so that people can give feedback on organization etc.

**Comment by choldgraf** [comment]
ok, @ryanlovett and I had a meeting and have considerably added to the list above. I'll try to step through most of this by the end of the weekend so that it's ready to go by Monday. When that's done, it'd be great if some people could take a look through what's there and make edits / rearrangements as they like.

**Comment by choldgraf** [comment]
Hey everybody, I've updated several of the sections in the wiki, and have added github issues for outstanding issues. Let's take commentary on those specific points to their respective issues, and I'm going to close this thread for now.

The documentation is in a more-or-less ready state for new instructors. But it'd be great if folks could take a look through it and make edits as needed.
