### ISSUE TITLE
Instructor test accounts

### ISSUE THREAD

**Issue by ryanlovett** [data-8/connector-instructors#4]
@deculler and @cboettig (in #3)  have both expressed an interest in being able to have non-admin accounts on JupyterHub for testing the student experience. Here are a couple of ways that might find their way into documentation:
1. A [SPA](https://berkeley.service-now.com/kb_view.do?sysparm_article=KB0010719).
   - Instructor needs to manually delete the account after the semester
2. A [CalNet guest account](https://berkeley.service-now.com/kb_view.do?sysparm_article=KB0010693)
   - Intentionally transitory
   - Really meant for non-campus people

In either case, the instructor would either personally add the account to JupyterHub via their own account with admin rights, or send the name of the account to an admin and have them do it.

**Comment by anthonysuen** [comment]
Thanks @ryanlovett ! Has anyone started a writing a workflow for the connectors yet? Ideally it should align with what documentation DS8 has already. Could someone link to me to the workflow documentation for DS8?

**Comment by cboettig** [comment]
@ryanlovett Thanks for bringing this up as an issue. 

Correct me if I'm wrong, but I think the account I currently have on ds8.berkeley.edu is essentially a 'student' account already, right? i.e. it gives me no elevated privileges over a student, and is automatically populated with material in the same way that students are?  Or is there a difference in how it behaves?

The SPA route does seem like the correct way to go for this kind of thing.  I wonder if it would actually make more sense the the SPA account is used by the instructor as the 'instructor privileged' account, rather than using their personal CalNet ID for that purpose?  For instance, if I understand correctly, a SPA account would allow an instructor to let a TA or other instructor use those credentials to login to the course alone, and, if necessary, could even be transferred between instructors.  Of course such sharing would be out of the question when those credentials are tied directly to the calnet id.

**Comment by ryanlovett** [comment]
@anthonysuen I'm not aware of any documentation for connector instructors and ds8 other than this repo, https://github.com/dsten/connector-instructors. I'd be happy to discuss it. I think it makes sense to start from any feedback from this past semesters' instructors and GSIs and port it into tips and docs for this semester. Items I'd anticipate people will want:
- Adding students
- Publishing notebooks (#3)
- Grading
- Creating instructor-owned student accounts (#4)

@cboettig Yes, you currently have a non-admin account. This is just because that is how all accounts had been created up to this point and we've lazy-loaded admin rights to people when needed.

GSIs have been distributing material by using a "distribute" script on the hub server. It hasn't discriminated between users so admins also receive the same files. On the hub server, GSIs have been entered into a group for sudoing the script.

A member of a SPA [uses their own CalNet credentials](https://berkeley.service-now.com/kb_view.do?sysparm_article=KB0010483) to authenticate to it. So an admin of the instructor SPA would add other instructors via https://idc.berkeley.edu/mmk. Instructors could then login to ds8 as the one SPA and share a single account. This would shift the admin-rights granting from JupyterHub to CalNet. It would also mean that instructors wouldn't have to create their own student testing accounts. Their personal accounts would be used for that while the SPA would be used for admin activities. Instructors would have to be careful not to step on each others files and toes within the one admin account.

**Comment by SamLau95** [comment]
@ryanlovett @cboettig @anthonysuen 

I believe I [outline a workflow](https://github.com/data-8/connector-instructors#workflow) in the readme for this repo. Is that what you're looking for?

In terms of distributing files to students, we are now transitioning to [the interact links](https://github.com/data-8/connector-instructors#distributing-notebooks) for all content instead of `ssh`ing into the servers.

@cboettig I've given you admin rights on the server so that you can add your students yourself.

**Comment by ryanlovett** [comment]
Sam, that workflow has /dsten/ repos. Just pointing that out in case you
intend to transition to /data-8/.

Regarding having instructors add students: if they're going to do so can
you please document that they need to obtain their students' official @
berkeley.edu addresses. The username is the part before the '@'. We can do
this in batch if we had GSI-level access to the bcourse. You'd create an
API token at bcourses then feed it to an altered version of this script
https://gist.github.com/ryanlovett/e9558f6e8c0b81d7dfca.

Real API access to course rosters at api-central.b.e won't land until March.

Ryan

**Comment by deculler** [comment]
Sam,
   This looks great.  I read through the workflow.  It seems clear as
bell.  I'll throw a notebook into my first lab just to try it out.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by deculler** [comment]
https://teaching.berkeley.edu/resources-faculty-new-berkeley

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by choldgraf** [comment]
hey all - is this issue taken care of? If so I will close...
